### ISSUE TITLE
Navigation bar overflowing on the homescreen.

### ISSUE THREAD

**Issue by Code-Beaker** [Exodia-OS/exodia-os.github.io#9]
the links and button overflow the navbar on the homescreen.

![image](https://github.com/user-attachments/assets/b1e47638-7eb5-41b4-9bc2-7835b172651b)

**Comment by awfixer** [comment]
This is because there is no code in the site to determine relative placement. We will have a fix for this soon

**Comment by Code-Beaker** [comment]
I have opened a pull request and fixed the navbar issue[overflowing content], please review and let me know
